name: Chocolatey Publish Pulsar

on:
  issues:
    types: [ labeled ]

jobs:
  draft_publish:
    if: contains(github.event.issue.labels.*.name, 'release')
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout Latest Code
      uses: actions/checkout@v3

    - name: Install Python Requirements
      run: pip install requests

    - name: Init New Version
      run: python init.py ${{ github.event.issue.title }}

    - name: Create Pull Request With Changes
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Draft ${{ github.event.issue.title }} Release
        branch: release-${{ github.event.issue.title }}
        delete-branch: true
        title: '[${{ github.event.issue.title }}] Draft Release'
        body: |
          Automated Draft of new Pulsar Chocolatey Release
        draft: false
