name: Chocolatey Test Installation

on: [ workflow_dispatch, pull_request]

jobs:
  tests:
    runs-on: windows-latest

    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v3

    - name: Build Current Version
      run: |
        cd ./pulsar
        choco pack

    - name: Install Current Version
      run: choco install pulsar --source .

    - name: Put Pulsar On the PATH
      run: |
        "$env:LOCALAPPDATA\Programs\Pulsar\" >> $env:GITHUB_PATH
        "$env:LOCALAPPDATA\Programs\Pulsar\resources\ppm\bin\" >> $env:GITHUB_PATH

    - name: Ensure Installation was successful
      run: |
        pulsar --version |
        ConvertFrom-String -PropertyNames Application,Delimiter,Version |
        Where-Object {$_.Application -eq "Pulsar" } >> $env:GITHUB_STEP_SUMMARY

    - name: Write Comment
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: $env:GITHUB_STEP_SUMMARY
